version: '3'
services:
  conda:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_conda
    ports:
    - "8888:8888"
    volumes:
    - .:/workdir
    tty: true
    stdin_open: true
